name: Release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yojigenserver/emby

on:
  push:
    tags:
      - v*

jobs:
  release:
      runs-on: ubuntu-latest
      
      permissions:
        contents: read
        packages: write
        
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            submodules: recursive
  
        - name: Login to GitHub Container Registry
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Build Image'
          run: |
            docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref }}
